export const katakana = [
  { character: "ア", romanji: "a" },
  { character: "イ", romanji: "i" },
  { character: "ウ", romanji: "u" },
  { character: "エ", romanji: "e" },
  { character: "オ", romanji: "o" },
  { character: "カ", romanji: "ka" },
  { character: "キ", romanji: "ki" },
  { character: "ク", romanji: "ku" },
  { character: "ケ", romanji: "ke" },
  { character: "コ", romanji: "ko" },
  { character: "サ", romanji: "sa" },
  { character: "シ", romanji: "shi" },
  { character: "ス", romanji: "su" },
  { character: "セ", romanji: "se" },
  { character: "ソ", romanji: "so" },
];

export const hiragana = [
  { character: "あ", romanji: "a" },
  { character: "い", romanji: "i" },
  { character: "う", romanji: "u" },
  { character: "え", romanji: "e" },
  { character: "お", romanji: "o" },
  { character: "か", romanji: "ka" },
  { character: "き", romanji: "ki" },
  { character: "く", romanji: "ku" },
  { character: "け", romanji: "ke" },
  { character: "こ", romanji: "ko" },
  { character: "さ", romanji: "sa" },
  { character: "し", romanji: "shi" },
  { character: "す", romanji: "su" },
  { character: "せ", romanji: "se" },
  { character: "そ", romanji: "so" },
];

export const kanji = [
  { character: "日", romanji: "nichi" },
  { character: "本", romanji: "hon" },
  { character: "人", romanji: "hito" },
  { character: "大", romanji: "dai" },
  { character: "学", romanji: "gaku" },
  { character: "中", romanji: "naka" },
  { character: "山", romanji: "yama" },
  { character: "川", romanji: "kawa" },
  { character: "田", romanji: "ta" },
  { character: "子", romanji: "ko" },
  { character: "水", romanji: "mizu" },
  { character: "火", romanji: "hi" },
  { character: "木", romanji: "ki" },
  { character: "金", romanji: "kin" },
  { character: "土", romanji: "tsuchi" },
  { character: "天", romanji: "ten" },
  { character: "気", romanji: "ki" },
  { character: "見", romanji: "mi" },
  { character: "行", romanji: "kou" },
  { character: "前", romanji: "zen" },
  { character: "後", romanji: "go" },
  { character: "生", romanji: "sei" },
  { character: "時", romanji: "ji" },
  { character: "今", romanji: "ima" },
  { character: "年", romanji: "nen" },
  { character: "名", romanji: "na" },
  { character: "高", romanji: "taka" },
  { character: "小", romanji: "shou" },
  { character: "白", romanji: "shiro" },
  { character: "赤", romanji: "aka" },
  { character: "青", romanji: "ao" },
  { character: "車", romanji: "kuruma" },
  { character: "電", romanji: "den" },
  { character: "門", romanji: "mon" },
  { character: "書", romanji: "sho" },
  { character: "語", romanji: "go" },
  { character: "食", romanji: "shoku" },
  { character: "飲", romanji: "in" },
  { character: "駅", romanji: "eki" },
  { character: "会", romanji: "kai" },
  { character: "社", romanji: "sha" },
  { character: "店", romanji: "ten" },
  { character: "道", romanji: "dou" },
  { character: "雨", romanji: "ame" },
  { character: "空", romanji: "sora" },
  { character: "海", romanji: "umi" },
  { character: "花", romanji: "hana" },
  { character: "魚", romanji: "sakana" },
  { character: "犬", romanji: "inu" },
  { character: "猫", romanji: "neko" },
];
